var fs = require('fs');
var path = require('path');

// Replace with your unique name
exports.appName = 'asv-push-project';

// Use your own Server Key as generated by Google Developer Console
// For more details, see http://developer.android.com/google/gcm/gs.html
exports.gcmServerApiKey = 'AAAApSt3pYc:APA91bHikZwlp0TFNmXCxDT81AJ6Bu9KpzqnoDTUZLaLOg3dakBzpUJenbp2_FnGlR9nagkI9CQSuW8E9ipWs6zipb580eJBtJw_xaM-xWfvBXkaIvyoi1g0eYB7lHk3l_A4qLrNYJ14';

// You may want to use your own credentials here
exports.apnsCertData = readCredentialsFile('apns_cert_dev.pem');
exports.apnsKeyData =readCredentialsFile('apns_key_dev.pem');


//--- Helper functions ---

function readCredentialsFile(name) {
  return fs.readFileSync(
    path.resolve(__dirname, 'credentials', name),
    'UTF-8'
  );
}
